# CI for Xcode Builder

before_script:
  - uname -a
  - whoami
  - pwd

build:
  tags:
    - iOS
  artifacts:
    paths:
      - artifacts/
  script:
    - SAFELOCATION=$(pwd) && echo $SAFELOCATION
    - rm -rf artifacts
    - mkdir artifacts    

    # # Submodule
    # - git config --global http.proxy http://192.168.54.138:10000
    # - git config --global https.proxy https://192.168.54.138:10000
    # - git submodule init
    # - git submodule update
    # - git config --global --unset http.proxy
    # - git config --global --unset https.proxy

    # Extract submodule from cache due to luck of GFW
    - tar -xvf ./submoduleCache.tar

    - xcodebuild -workspace ./RepoSync.xcworkspace -list

    # Build
    - cd $SAFELOCATION
    - rm -rf Packages/*
    - xcodebuild clean
    - xcodebuild -workspace ./RepoSync.xcworkspace -scheme RepoSync
    - cp ./CI/* $SAFELOCATION/artifacts/

